language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: F/rrP5lOIWgQLpxUgCZ0MPWsB3ilpd+k2tUJPav3auFsQfNnHVhJqQ579Ela8FvsEMJJZJgPLt/W0OmgjdJ4RsIoXlTmRHjiHY8Z5UjxhNETTg8UJVOeEPJpOZhZIR6oneogZdOC4Vlx+gzfQgMN44Fbl3CRYHcdjZHWpfWMx9fNVpkBUpjoQigclkn4MCz+MtWvwd2wN8a8VPT9HahhxLYDbgMrO85VmxnJmfod7cfF3QY5zMhPY86MxwToGz+bO6xSq9q/+uGnFS9w1W3SVtrK1n3OOnZmGvno+73Uw0oIYbMMdBEONWhrhk0No1MjQpWco23e0NQXMYYXdvQc/JYi+9S0VvBYlCKb5jx40CeWxg2n/UDa0G+Qo5Q56Rul9ny2I3aiLMtnRuraiDA3c3ie1VEmqur1P/Oqw0wJqko/gwtXmQge4/TczDBo1mMzwEU0CpzTrDTb+6sFzJdKej2fVb6w+9b/SD9BAWhRRAcjcOGNgeeQMaSVX537nHZSZSmDRjplKS4d3iNF7gutR4NrV0CAC9q6++jsFHL9FlAGziXtO4zftJWoj4nLrz9ehwRvH2Rpp7ZT1sgU40fRr/DxIFWT1QPx6ROAYt1EUqZgWCPHVeEY/icGjtYcM4MbUaoQaF6hH5AG9rHTySAlHgbBoWWXsFBXUqdN0uC8Vv4=
  on:
    tags: true
    branch: master
    repo: DEGJS/formValidation-pattern
